### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by retep998** [MrTJP/ForgeRelocationFMP#2]
I made a simple frame setup using AE2 and when I tried to activate it the server portion of Minecraft crashed.
![](http://puu.sh/fm4Hl/d474b54af6.jpg)
```
[21:39:55] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel ForgeMultipart
java.lang.NullPointerException
	at codechicken.multipart.handler.MultipartCPH$.handlePacket(packethandlers.scala:48) ~[MultipartCPH$.class:?]
	at codechicken.lib.packet.PacketCustom$ClientInboundHandler.handle(PacketCustom.java:98) ~[PacketCustom$ClientInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_76]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[21:39:55] [Server thread/INFO]: retep998 lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[21:39:55] [Server thread/INFO]: retep998 left the game
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.call(Reflector.java:451)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.getTileEntityBoundingBox(RenderGlobal.java:3361)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:735)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.vec.Cuboid6.enclose(Cuboid6.java:146)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at scala.collection.immutable.List.foreach(List.scala:383)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient.getRenderBoundingBox(TileMultipart.scala:510)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.call(Reflector.java:451)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.getTileEntityBoundingBox(RenderGlobal.java:3361)
[21:39:55] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:735)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1688)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.vec.Cuboid6.enclose(Cuboid6.java:146)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at scala.collection.immutable.List.foreach(List.scala:383)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient.getRenderBoundingBox(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
[21:39:56] [Server thread/INFO]: Stopping singleplayer server as player logged out
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.call(Reflector.java:451)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.getTileEntityBoundingBox(RenderGlobal.java:3361)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:735)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.vec.Cuboid6.enclose(Cuboid6.java:146)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at scala.collection.immutable.List.foreach(List.scala:383)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient.getRenderBoundingBox(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Reflector.call(Reflector.java:451)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.getTileEntityBoundingBox(RenderGlobal.java:3361)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:735)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1688)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1305)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.NullPointerException
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.lib.vec.Cuboid6.enclose(Cuboid6.java:146)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient$$anonfun$getRenderBoundingBox$1.apply(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at scala.collection.immutable.List.foreach(List.scala:383)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at codechicken.multipart.TileMultipartClient.getRenderBoundingBox(TileMultipart.scala:510)
[21:39:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 17 more
[21:39:56] [Server thread/INFO]: Stopping server
[21:39:56] [Server thread/INFO]: Saving players
[21:39:56] [Server thread/INFO]: Saving worlds
[21:39:56] [Server thread/INFO]: Saving chunks for level 'Flat'/Overworld
[21:39:56] [Server thread/INFO]: Saving chunks for level 'Flat'/Nether
[21:39:56] [Server thread/INFO]: Saving chunks for level 'Flat'/The End
[21:39:56] [Server thread/INFO] [FML]: Unloading dimension 0
[21:39:56] [Server thread/INFO] [FML]: Unloading dimension -1
[21:39:56] [Server thread/INFO] [FML]: Unloading dimension 1
[21:39:56] [Server thread/INFO] [FML]: Applying holder lookups
[21:39:56] [Server thread/INFO] [FML]: Holder lookups applied
```

**Comment by isavegas** [comment]
That's not caused by ForgeRelocationFMP, which only handles ForgeMultiPart microblocks. Forge Relocation offers a plugin system that allows one to write handlers for various block types and mods, and until someone writes one for AE2, there's little to be done but wait.
