### ISSUE TITLE
ThermalDynamics conduits

### ISSUE THREAD

**Issue by Paul17041993** [MrTJP/ForgeRelocationFMP#3]
When moving a conduit from ThermalDynamics, the game will crash from a failed cast, possibly a fault with the TE handling for movement or otherwise a T.D. bug/compatibility issue. Will be mirrored to CoFH, but have not tested with other frame mods yet.

Stacktrace:
	at cofh.thermaldynamics.block.TileTDBase.getDuctType(TileTDBase.java:734)
	at cofh.thermaldynamics.duct.energy.TileEnergyDuct.isConnectable(TileEnergyDuct.java:69)
	at cofh.thermaldynamics.block.TileTDBase.handleSideUpdate(TileTDBase.java:402)
	at cofh.thermaldynamics.block.TileTDBase.onNeighborBlockChange(TileTDBase.java:329)
	at cofh.core.block.BlockCoFHBase.func_149695_a(BlockCoFHBase.java:185)

**Comment by simon816** [comment]
Need the whole error message, not just the stacktrace. Preferably the whole log.
It seems to be suggesting thermal dynamics is the problem here, however I cannot be sure.

**Comment by MrTJP** [comment]
Wouldn't bother trying to fix it, the movement system is going to drastically change soon.

**Comment by Paul17041993** [comment]
from KingLemming; "If the duct is actually moved correctly, this shouldn't happen. Funky Locomotion seems to get it right.
Basically, this should crash and crash hard, because it means that ProjectRed is not properly removing old tiles."
